<FormEditorScreen>:
    name: 'form_editor'
    id: form_editor_screen
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,1

        NavBar:
            id: navbar
            size_hint: 1, .1
            pos_hint: {'center_y': 0.5,'center_x': 0.5}

        StackLayout:
            orientation: 'lr-tb'  # Left to right, top to bottom
            size_hint: 1, .8
            padding: 10, 10
            spacing: 10
            id: forms_list