<ProfileScreen>:
    name: 'profile'
    id: profile_screen
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,1

        NavBar:
            id: navbar
            size_hint: 1, .1
            pos_hint: {'center_y': 0.5,'center_x': 0.5}

        Label:
            text: 'Profile Screen'
            size_hint: 1, .9
            pos_hint: {'center_y': 0.5,'center_x': 0.5}
            font_size: 30