<UsersScreen>:
    name: 'users_screen'
    id: users_screen
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,1

        NavBar:
            id: navbar
            size_hint: 1, .1
            pos_hint: {'center_y': 0.5,'center_x': 0.5}

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 1

            Label:
                text: 'Users'
                size_hint: .1, .1